### ISSUE TITLE
401 Error

### ISSUE THREAD

**Issue by praimo666** [jackmusick/connectwise-control-api#1]
Hello Jack,

I'm currently trying to use your API to obtain the number of currently active sessions in my screenconnect instance. 

I'm also using the latest version of your API that fixed access to version 6.9. However I still get the 401 security Exception error below:

StatusCodeError: 401 - {"errorType":"SecurityException","message":"Needs permission","detail":null

The code I'm executing is simply this:

async function executeAsyncTask () {
  try{
      await cc.getSessions();
  }catch(e){
      console.log(e);
  }
}

**Comment by wad11656** [comment]
Same issue here. Is this API officially defunct/unsupported, or is there something wrong in our setup?

**app.js**
```
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const cc = require('connectwise-control-api')('https://control.equinoxits.com/', 'My@ActualEmail.com', 'MyActualPassword');

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
});

async function asyncCall() {
  console.log('calling');
  const result = await cc.getSessionGroups();
  console.log(result);
}
server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});

asyncCall();
```

**Console output**
```
(node:19108) UnhandledPromiseRejectionWarning: StatusCodeError: 401 - {"errorType":"SecurityException","message":"Needs permission","detail":null}
    at new StatusCodeError (V:\...\CW Control API\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (V:\...\CW Control API\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (V:\...\CW Control API\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (V:\...\CW Control API\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (V:\...\CW Control API\node_modules\request\request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (V:\...\CW Control API\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:19108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
